### ISSUE TITLE
The Twig_Function_Method class is deprecated since version 1.12

### ISSUE THREAD

**Issue by 7eey** [gibilogic/tinymce-bundle#13]
Hi,

In method "getFunctions" of StfalconTinymceExtension class can you change the line
<code>'tinymce_init' => new \Twig_Function_Method($this, 'tinymceInit', array('is_safe' => array('html')))</code>
by
<code>new \Twig_SimpleFunction('tinymce_init', [$this, 'tinymceInit'], ['is_safe' => ['html']])</code>

Thks
Jérém

**Comment by zanardigit** [comment]
Thank you! This is already fixed in version **1.0.1**, available on Packagist, and in `master` branch.

**Comment by 7eey** [comment]
Thank you too!
