### ISSUE TITLE
sensio/distribution-bundle version dependency

### ISSUE THREAD

**Issue by steven-pribilinskiy** [gibilogic/tinymce-bundle#15]
We use [`symfony-standard 2.7`](https://github.com/symfony/symfony-standard/blob/2.7/composer.json) framework and it depends on `sensio/distribution-bundle ~4.0`.
Could the version of `distribution-bundle` bundle raised to `~4.0` for tinymce-bundle?

**Comment by zanardigit** [comment]
Sort of. If we just change it to 

```
"sensio/distribution-bundle": "~4.0"
```

the package will not work anymore on previous Symfony versions, which does not really make sense.  We have two options.

# 1. Open to any future version

```
"sensio/distribution-bundle": ">=3.0.12"
```

This is coherent with `"symfony/symfony": ">=2.1"`.

# 2. Only add the 4.0 version

```
"sensio/distribution-bundle": "~3.0|~4.0,>=3.0.12"
```

@pribilinskiy @Ingannatore what do you think is best?

**Comment by steven-pribilinskiy** [comment]
@zanardigit sure, the 2nd version is better.
Didn't knew about the `|` in semver

**Comment by MisatoTremor** [comment]
@zanardigit @pribilinskiy This again breaks for symfony-standard 2.8 & 3.0 which require ~5.0 and ^5.0 of distribution-bundle respectively.
Therefore I'd say the first option should be used.
The second option will always need to be changed when newer symfony-standard versions require newer distribution-bundle. With option one this is not needed and it only needs to be changed if there'll ever be a distribution-bundle version released which breaks BC.

**Comment by steven-pribilinskiy** [comment]
+1 for `>=3.0.12`

**Comment by nykopol** [comment]
thanks @zanardigit for the fix. Can you please tag a new version that include that ?

**Comment by zanardigit** [comment]
Tagged 1.1.1. Will be available on Packagist shortly.

**Comment by MisatoTremor** [comment]
@zanardigit 1.1.1 is around since october, but it points to the "old" change commit (5c612eb).
Or did you mean that you will create a new tag (1.1.2) for the new commit (50da21c)?

**Comment by zanardigit** [comment]
My mistake, re-tagged correctly to the latest change (https://github.com/gibilogic/tinymce-bundle/commit/50da21c9bff4e405e4a591cb47a595a5e6a648ac).

**Comment by MisatoTremor** [comment]
Thanks :+1:
