### ISSUE TITLE
sensio/distribution-bundle version dependency [reopened]

### ISSUE THREAD

**Issue by steven-pribilinskiy** [gibilogic/tinymce-bundle#16]
reopening #15 to make the `tinymce-bundle` compatible with future `symfony` releases by updating the `distribution-bundle` version dependency to:

```
"sensio/distribution-bundle": ">=3.0.12"
```

**Comment by zanardigit** [comment]
@pribilinskiy not sure why you opened an issue (#16) just to say you have re-opened another issue (#15). I'm closing this one, let me know if I missed something.
