### ISSUE TITLE
Configuration as an open parameter that would be passed as-is to TinyMCE

### ISSUE THREAD

**Issue by Ingannatore** [gibilogic/tinymce-bundle#19]
This is an idea/proposition born from #18; it's someything I also had in mind since months ago.

TinyMCE has a lot of configuration parameters (see https://www.tinymce.com/docs/configure) but our bundle implements a small subset only; there is also the added complexity of Symfony config validation (see https://github.com/gibilogic/tinymce-bundle/blob/master/src/DependencyInjection/Configuration.php).

The solution: use a single "open parameter" that will be JSON-serialized and passed _as-is_ to TinyMCE; no more config validation and no more "I need to use that TinyMCE's parameter but we don't have it configured inside the bundle" problems.

What do you guys think about that?

**Comment by zanardigit** [comment]
Let's do it.
