### ISSUE TITLE
The packagist

### ISSUE THREAD

**Issue by RubenHarms** [gibilogic/tinymce-bundle#2]
@zanardigit, can you notice me when this fork is registered to the packagist?

**Comment by zanardigit** [comment]
It is already: https://packagist.org/packages/gibilogic/tinymce-bundle.
We have just published it as it is, later we will add some goodies.

**Comment by RubenHarms** [comment]
Thanks @zanardigit! Package has been replaced :+1:

**Comment by Ingannatore** [comment]
I've also activated the auto-update of the package on Packagist.
