### ISSUE TITLE
Error on composer install

### ISSUE THREAD

**Issue by Ingannatore** [gibilogic/tinymce-bundle#4]
After launching the command

```
php composer.phar install
```

in the project folder, I get the following output:

> Writing lock file
> Generating autoload files
> Class Stfalcon\Bundle\TinymceBundle\Composer\ScriptHandler is not autoloadable, can not call post-install-cmd script

**Comment by RubenHarms** [comment]
I never wrote a post-install-cmd script, but maybe its related to #3

**Comment by Ingannatore** [comment]
It's not your fault: I tried that before your pull request; it seems it's an autoloading-related problem.

**Comment by RubenHarms** [comment]
Ah okay, i got that.

**Comment by RubenHarms** [comment]
I can't reproduce the bug! Did you tried to remove from composer and re-add it again?

**Comment by Ingannatore** [comment]
Can you confirm me if inside your test the symlink has been successfully created?

**Comment by RubenHarms** [comment]
I can't confirm that. After removing the symlink it did not came back. The TinymceSymlinkCommand works fine. It's the ScriptHandler!

**Comment by Ingannatore** [comment]
I agree: by switching to `psr-4` autoloading both the `post-install` and `post-update` commands work but they both terminate with an exception.

I'm closing this ticket and then I'll create a new one for that exception.
@RubenHarms: thanks for your help :)
