### ISSUE TITLE
Both post-install and post-update commands terminate with an exception

### ISSUE THREAD

**Issue by Ingannatore** [gibilogic/tinymce-bundle#5]
This is the (pretty useless) error message:

> [Exception]
> An error occurred while creating symlink/home/matteo/Resources/public/vendor/tinymce

And this is the stack trace:

```
Exception trace:
 () at /home/matteo/Sviluppo/tinymce-bundle/src/Command/TinymceSymlinkCommand.php:72
 Stfalcon\Bundle\TinymceBundle\Command\TinymceSymlinkCommand::createSymlink() at /home/matteo/Sviluppo/tinymce-bundle/src/Composer/ScriptHandler.php:32
 Stfalcon\Bundle\TinymceBundle\Composer\ScriptHandler::postInstallSymlinkTinymce() at phar:///home/matteo/Sviluppo/tinymce-bundle/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:211
 Composer\EventDispatcher\EventDispatcher->executeEventPhpScript() at phar:///home/matteo/Sviluppo/tinymce-bundle/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:167
 Composer\EventDispatcher\EventDispatcher->doDispatch() at phar:///home/matteo/Sviluppo/tinymce-bundle/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:92
 Composer\EventDispatcher\EventDispatcher->dispatchScript() at phar:///home/matteo/Sviluppo/tinymce-bundle/composer.phar/src/Composer/Installer.php:344
 Composer\Installer->run() at phar:///home/matteo/Sviluppo/tinymce-bundle/composer.phar/src/Composer/Command/InstallCommand.php:131
 Composer\Command\InstallCommand->execute() at phar:///home/matteo/Sviluppo/tinymce-bundle/composer.phar/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at phar:///home/matteo/Sviluppo/tinymce-bundle/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at phar:///home/matteo/Sviluppo/tinymce-bundle/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at phar:///home/matteo/Sviluppo/tinymce-bundle/composer.phar/src/Composer/Console/Application.php:146
 Composer\Console\Application->doRun() at phar:///home/matteo/Sviluppo/tinymce-bundle/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at phar:///home/matteo/Sviluppo/tinymce-bundle/composer.phar/src/Composer/Console/Application.php:82
 Composer\Console\Application->run() at phar:///home/matteo/Sviluppo/tinymce-bundle/composer.phar/bin/composer:43
 require() at /home/matteo/Sviluppo/tinymce-bundle/composer.phar:25
```

**Comment by RubenHarms** [comment]
Try to remove the @ before the symlink function online 71 in TinymceSymlinkCommand.php to see the real error. On what platform do you test?

**Comment by Ingannatore** [comment]
I did a bit of refactoring and now the symlink creation works; can you please test it too?

**Comment by RubenHarms** [comment]
The scripthandler works only when i run `composer run-script post-install-cmd` in the _./vendor/gibilogic/tinymce-bundle_ folder of my project. The symlink does not work with the `composer install` command in the root of my project. Something is still wrong...

**Comment by Ingannatore** [comment]
Results of the command `composer install --verbose` from inside the project:

```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Analyzed 84 packages to resolve dependencies
Analyzed 118 rules to resolve dependencies
Nothing to install or update
Generating autoload files
> post-install-cmd: Stfalcon\Bundle\TinymceBundle\Composer\ScriptHandler::createSymlink
```

Results of the command `composer install --verbose` from inside a Symfony 2 project:

```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Analyzed 118 packages to resolve dependencies
Analyzed 238 rules to resolve dependencies
Nothing to install or update
Generating autoload files
> post-install-cmd: Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> post-install-cmd: Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> post-install-cmd: Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
Clearing the cache for the dev environment with debug true
> post-install-cmd: Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets
Trying to install assets as symbolic links.
Installing assets for Symfony\Bundle\FrameworkBundle into web/bundles/framework
The assets were installed using symbolic links.
Installing assets for Stfalcon\Bundle\TinymceBundle into web/bundles/stfalcontinymce
The assets were installed using symbolic links.
Installing assets for Sensio\Bundle\DistributionBundle into web/bundles/sensiodistribution
The assets were installed using symbolic links.
> post-install-cmd: Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile
> post-install-cmd: Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::removeSymfonyStandardFiles
> post-install-cmd: Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::prepareDeploymentTarget
```

I still think there is something wrong with the autoloader, but it should gives us some kind of error.

**Comment by Ingannatore** [comment]
I'm a damn noob: Composer executes all the callbacks defined inside its `composer.json`; by installing our package inside a Symfony 2 application, Composer will be using the application's `composer.json` (without our `post-install` and `post-update` scripts). That's why our "internal" callbacks fire only inside our package's folder.

**Comment by RubenHarms** [comment]
Good discovery! But strange. MopaBootrstrap has the same code in it's composer file...

**Comment by Ingannatore** [comment]
You can read more about this issue [here](https://github.com/composer/composer/issues/1193).

Quoting Seldaek:

> There are moderate security concerns with doing that, but we just did not do it because we were not sure whether it was a good idea. We named the events in a way that we can add a post-install script that would be executed on the package when it is actually installed, so it should be no problem to add without breaking anything.
> 
> That said, I don't think it's a huge drawback that users of your lib must add the scripts to their own composer.json.. It is one extra step but at least it makes it very obvious what is executed, and it's easy to remain in control as a user, so I would still favor the status quo.

**Comment by MisatoTremor** [comment]
_Edit: OK this now needs context :D_
Mopa has these lines in the `composer.json` for CI and testing. I added them so this bundle would be ready for these.

But yes, `post-*` will not automatically executed in a symfony project. But that's actually good, as the projects maintainer can choose to include them in the projects `composer.json` or use the console commands.

**Comment by RubenHarms** [comment]
As i can see, mopa implemented it for testing purposes see:
https://github.com/phiamo/MopaBootstrapBundle/commit/4d7ce4784d91039df6f547eb1e02eb3b95d3069f

**Comment by MisatoTremor** [comment]
Mhh, I just saw that you removed the commands when refactoring. These should really stay there for flexibility.

**Comment by RubenHarms** [comment]
:+1: I agree with that. Just update the documantation with the command or post-install-cmd

**Comment by MisatoTremor** [comment]
Good point, easy to miss the possibility if not documented.

**Comment by Ingannatore** [comment]
I've moved the symlink creation inside the console command; the `post-install` and `post-update` script executes that command.

**Comment by Ingannatore** [comment]
@RubenHarms let me know if you can test the latest changes, thanks.

**Comment by RubenHarms** [comment]
I can't test it right:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for gibilogic/tinymce-bundle dev-master -> satisfiable by gibilogic/tinymce-bundle[dev-master].
    - gibilogic/tinymce-bundle dev-master requires sensio/distribution-bundle ^4.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
ruben@ruben-System-Product-Name:/var/www/domains/hootcashback$
```

I use `sensio/distribution-bundle" : "~3.0.12.`

Can we fix that problem?

**Comment by Ingannatore** [comment]
@RubenHarms my bad; fixed and pushed.

**Comment by RubenHarms** [comment]
I got this error:

```
  [RuntimeException]                                                                                                                                                                                                                                                                                           
  The autoloader expected class "Stfalcon\Bundle\TinymceBundle\Command\SymlinkCommand" to be defined in file "/var/www/domains/hootcashback/vendor/gibilogic/tinymce-bundle/src/Command/SymlinkCommand.php". The file was found but the class was not in it, the class name or namespace probably has a typo.  
```

I fixed this issue in #10 

Could you please merge this one?

**Comment by MisatoTremor** [comment]
I'm working on a fix for the old command and script handler (better error messages etc.) and open a PR in a couple of days. The current solution unfortunately lacks the mirroring function needed on systems lacking symlink support (e.g. old Windows). Also the method used to get the path to TinyMCE isn't really safe :D

**Comment by RubenHarms** [comment]
That's great @MisatoTremor. Until that we should fix this problem.

**Comment by MisatoTremor** [comment]
:+1: Indeed!

**Comment by Ingannatore** [comment]
@MisatoTremor I've used the `symlink` function of Symfony's `Filesystem` component (doc [here](http://api.symfony.com/2.7/Symfony/Component/Filesystem/Filesystem.html#method_symlink)); it has a `$copyOnWindows` flag (as 3rd parameter).

**Comment by RubenHarms** [comment]
Okay, still one problem before we're complete. #11

**Comment by RubenHarms** [comment]
The bundle works fine for me now! Let's create a 1.1 branch! #9

**Comment by MisatoTremor** [comment]
@Ingannatore Looks good, I'll test this.

**Comment by zanardigit** [comment]
@RubenHarms @MisatoTremor @Ingannatore no need to create a 1.1 branch; as soon as all of you can confirm the current `master` branch is ok, I will release a v1.1.0.

Thank you so much for your contribution and help!

**Comment by Ingannatore** [comment]
Version 1.1 is live! https://packagist.org/packages/gibilogic/tinymce-bundle#1.1.0
